### PR TITLE
Convert to Caddy 0.9 plugin format

### PR DESCRIPTION
**Pull request by mholt**
According to: https://github.com/mholt/caddy/wiki/Converting-Add-ons-to-Plugins

This was just a quick edit from the GitHub website, you should make sure this compiles. ;) Also don't forget to change any references in other files, I didn't get them all here.

### CODE REVIEW

**Comment by mholt** [comment]
Oh and I forgot to register the plugin, add this to your config.go file:

```go
func init() {
	caddy.RegisterPlugin("jwt", caddy.Plugin{
		ServerType: "http",
		Action:     Setup,
	})
}
```

**Comment by mholt** [comment]
@BTBurke Once Caddy 0.9 is released, I will not be able to include this plugin on the download page until the plugin is updated to work with Caddy 0.9. 😞 (Sorry again about the breaking change.)

**Comment by BTBurke** [comment]
Ok. I'll work on it as soon as I can.

**Comment by mholt** [comment]
#10 is better / more thorough!

**Pull request closed without merging**
