### PR TITLE
Added redirect option for simple login flows.

### PR DESCRIPTION
**Pull request by smancke**
Hi,  here is a proposal for a redirect option. I hope, you like it.

I have started a login middleware for caddy at https://github.com/tarent/loginsrv
With this redirect option, both play nicely together.

### CODE REVIEW

**Comment by BTBurke** [comment]
Thanks for your contribution.  Its thanksgiving over here so I won't have a chance to look at it in detail until next week. 

Looks really useful.  I thought something like this was already possible with other Caddy commands, so I'll have to do a little research before I merge this.

**Comment by smancke** [comment]
Happy Thanksgiving! No need to rush :)

I already checked the caddy commands before implementing this, but didn't found a solution:
* The config `error 401 /login` only tries to deliver local file contents, no redirect is possible.
* The `redir` directive can only be configured using request parameters, not with the response status.

**Comment by smancke** [comment]
Hi Bryan,
is there any change to get this in?

**Comment by BTBurke** [comment]
I'm going to put this in. I'm moving internationally right now so haven't had time to mess with it.

**Comment by smancke** [comment]
ok, cool!

**Comment by yannouchou** [comment]
This works really well. I'd like to suggest an extension allowing to specify a different redirection URI for cases when the token is absent/invalid/expired (meaning you have to go through the login flow) and when it's rejected by the allow/deny authorization rules (meaning the flow would typically stop here with an access denied message).

The distinction is made in the return codes, so it would make sense to consider it also in the redirects.

It seems doable but unfortunately I'm not familiar enough with Go to submit a PR... Is this something you could consider implementing?

**Pull request merged**
