### PR TITLE
Adding the support for the configurable token sources.

### LINKED ISSUE #38: Loading cookie with alternative name
I'm trying to use Caddy to set up SSO between some services that are proxied by Caddy on different subdomains. This works pretty well, by setting the `cookie-domain` of the login plugin to a common domain all these services share. However, I'd like to be able to change the cookie name, as the default name "jwt_token" seems pretty generic, which I think could easily be overwritten by a careless service. `http.login` supports the `cookie_name` directive, but as far as I can tell, there's no equivalent in caddy-jwt.

### PR DESCRIPTION
**Pull request by igor-petruk**
This includes the actual list of checks and customisations such as cookie or query param names. Fixes #38.

### CODE REVIEW

**Comment by igor-petruk** [comment]
@BTBurke Is there anything I can improve in the pull request? :)

**Comment by igor-petruk** [comment]
Oh, I see. No problem. Have a great time!

**Comment by igor-petruk** [comment]
Any chance to take a look now? :) I just wanted to try it from the binary on caddyserver.com

**Comment by BTBurke** [comment]
Looks good.  Appreciate the contribution.

**Comment by BTBurke** [comment]
I just deployed it via the caddy website.  It's version 3.7.0.  Give it a shot and let me know if you have any problems.

**Comment by igor-petruk** [comment]
Hi.

Thanks! Everything works as expected.

**Pull request merged**
