### PR TITLE
Convert to Caddy 0.9 plugin format

### PR DESCRIPTION
**Pull request by namsral**
- Add init function to register the plugin
- Add OnStartup and GetConfig to the Setup function to register plugin
- Delete obsolete import paths and added new

Followed plugin update guide at:
	https://github.com/mholt/caddy/wiki/Converting-Add-ons-to-Plugins

### CODE REVIEW

**Comment by mholt** [comment]
@BTBurke I know you're busy, but if you can merge this in today or early tomorrow, I can keep it on the download page since the release is happening soon. Otherwise I'll have to take it off until it's compatible.

**Comment by namsral** [comment]
@mholt You're free to use my fork while BTBurke merges the PR.

https://github.com/namsral/caddy-jwt

**Comment by mholt** [comment]
@namsral Thanks! I'll look into that come tomorrow. Sleepy time now ;)

**Comment by BTBurke** [comment]
@namsral @mholt Just got it merged.  Sorry about the delay.  Appreciate the assist.

**Comment by mholt** [comment]
Perfect, I'll check it out today and update the site accordingly!

**Comment by mholt** [comment]
Added it to the download page again. Thanks!

**Pull request merged**
